### ISSUE TITLE
Support prefixes for issues

### ISSUE THREAD

**Issue by rsids** [stevemao/conventional-commits-parser#11]
Currently, only issues prefixed with a # or a GH- are recognised as an issue. When using an issue tracker like JIRA, issues can have all sorts of prefixes. My suggestion is to make the prefix configurable, so you can set it like this:
issuePrefix: ["BB-", "PROJECT-", "WHATEVER-"]

**Comment by stevemao** [comment]
Not sure how to fix this... #4
There are three links in that issue and I was trying to make the regex work for those use cases. Do you have any reference of how JIRA references issues? does it have to have a `#` before the number? in your example it looks like you have to have a `-` before the number? So makebe we should make the `#` configurable?

**Comment by stevemao** [comment]
I think this is a good idea, we should make the `(?:gh-|#)` configurable.

**Comment by rsids** [comment]
Jira issues are in the form of [PROJECTNAME]-[ISSUENUMBER], which translates in the url as [url to jira]/browse/[PROJECTNAME]-[ISSUENUMBER],

So an issue in the project FOO would look like FOO-123 and have the url http://jira.com/browse/FOO-123

Ik think the most versatile wat is indeed to make the prefix configurable. (And maybe have the gh- and # prefixes by default)

**Comment by stevemao** [comment]
I have pushed the rewrite to the master branch of `conventional-changelog`
The url should be configurable at https://github.com/stevemao/conventional-commits-writer. Its using handlebars template with customised context variables (open an issue there if you can't do it). 
In the rewrite we have https://github.com/ajoslin/conventional-changelog/tree/master/hosts where you put your default settings for different hosts.
I think we can make an option `issuePrefix` here defaults to `'#'`, and make `'gh-'` and `'#'` as defaults at https://github.com/ajoslin/conventional-changelog/blob/master/hosts/github.json

**Comment by stevemao** [comment]
https://github.com/ajoslin/conventional-changelog/pull/60
