### ISSUE TITLE
referencing a commit in parenthesis results in a parsing error

### ISSUE THREAD

**Issue by bcoe** [stevemao/conventional-commits-parser#27]
the following commit message:

`fix: upgraded dependencies, switched back to angular format (fixes #27), pinned shelljs to version that works with nyc (#30)`

results in a corrupt commit entry:

`* upgraded dependencies, switched back to angular format (fixes [#27](https://github.com/conventional-changelog/standard-version/issues/27)), pinned shelljs to version that works with nyc ([#30](https://github.com/conventional-changelog/standard-version/issues/30))([3f51e94](https://github.com/conventional-changelog/standard-version/commit/3f51e94)), closes [#27](https://github.com/conventional-changelog/standard-version/issues/27) [(#30](https://github.com/(/issues/30)`

the underlying cause seems to be the way references (`fixes #foo` are handled).

**Comment by stevemao** [comment]
The regex is a bit too loose. Smilar: #26

**Comment by bcoe** [comment]
@stevemao is there an easy way for an upstream library to disable the logic that replaces `fixes #foo` with:

`,closes #32` until we fix this regex, it would be nice to prevent this behavior in `standard-version`.

**Comment by stevemao** [comment]
Use a custom template and remove the "commit references" part. https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/templates/commit.hbs#L22-L51
